import Head from "next/head";

export default function About() {
  return (
    <>
      <Head>
        <title>NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>KS</h1>
      </main>
    </>
  );
}

// export async function getStaticProps() {
//静态
// }

export async function getServerSideProps() {
  // 动态计算：每次请求都会执行一次
}
